# [build]
builder = "nixpacks"

# Optional: If you need to specify a Nixpacks plan
# plan = "path/to/your/nixpacks.toml"  # Or "nixpacks.toml" if it's in the root

# Optional: Build arguments for Nixpacks
# buildArgs = { MY_VAR = "my_value" }

# Optional: Specify a start command. If not present, Nixpacks will infer one.
startCommand = "python your_script.py" # Replace with your start command
